version: '2'
services:
  db:
    container_name: postgres_items
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=localdb
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  pgdata: {}